[package]
name = "edif"
version = "0.1.0"
authors = ["Shotaro Yamada <sinkuu@sinkuu.xyz>"]
edition = "2018"

[dependencies]
combine = "3.5.2"
anyhow = "1"
string_cache = "0.8"
fxhash = "0.2.1"
petgraph = "0.4.13"

[build-dependencies]
string_cache_codegen = "0.5"
